<a href="https://colab.research.google.com/github/VadymBoyko/DS-HW01/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
a1 = np.arange(1, 11)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
a2 = np.zeros((3, 3))
print(a2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
a3 = np.random.randint(1, 11, size=(5, 5))
print(a3)

[[ 9  9  8  8  5]
 [ 2  3  6  1  9]
 [ 7  3  8  5  1]
 [10  2  5  1  5]
 [ 8  2  2  3  1]]


In [7]:
a4 = np.random.rand(4, 4)
print(a4)

[[0.55103847 0.37574492 0.57956819 0.27324043]
 [0.28505802 0.94407906 0.34415121 0.3895758 ]
 [0.41938117 0.74960708 0.68575488 0.87762027]
 [0.43994071 0.45991471 0.18957592 0.33942009]]


In [9]:
a5_1 = np.random.randint(1, 11, size=5)
a5_2 = np.random.randint(1, 11, size=5)
print(a5_1)
print(a5_2)
print('ADD:', a5_1 + a5_2)
print('SUB:', a5_1 - a5_2)
print('MUL:', a5_1 * a5_2)

[6 6 9 7 6]
[ 4 10 10 10 10]
ADD: [10 16 19 17 16]
SUB: [ 2 -4 -1 -3 -4]
MUL: [24 60 90 70 60]


In [10]:
a6_1 = np.random.randint(1, 101, size=7)
a6_2 = np.random.randint(1, 101, size=7)
print(a6_1)
print(a6_2)
print(np.dot(a6_1, a6_2))

[ 2 92 73 84 15 17 36]
[63 38 63 71 77 49 35]
17433


In [13]:
a7_1 = np.random.randint(1, 11, size=(2, 2))
a7_2 = np.random.randint(1, 11, size=(2, 3))
print(a7_1)
print(a7_2)
print(np.dot(a7_1, a7_2))

[[ 9  5]
 [ 2 10]]
[[ 2  9  3]
 [ 5  8 10]]
[[ 43 121  77]
 [ 54  98 106]]


In [14]:
a8 = np.random.randint(1, 11, size=(3, 3))
print(a8)
print(np.linalg.inv(a8))

[[8 4 2]
 [3 7 7]
 [9 8 3]]
[[ 0.24647887 -0.02816901 -0.09859155]
 [-0.38028169 -0.04225352  0.35211268]
 [ 0.27464789  0.1971831  -0.30985915]]


In [15]:
a9 = np.random.rand(4, 4)
print(a9)
print(a9.T)

[[0.33424894 0.00217616 0.94952016 0.82132342]
 [0.75193469 0.65039617 0.71740703 0.67238169]
 [0.08570975 0.31176141 0.52447887 0.35897844]
 [0.95496652 0.82866022 0.70981301 0.19536311]]
[[0.33424894 0.75193469 0.08570975 0.95496652]
 [0.00217616 0.65039617 0.31176141 0.82866022]
 [0.94952016 0.71740703 0.52447887 0.70981301]
 [0.82132342 0.67238169 0.35897844 0.19536311]]


In [16]:
a10_1 = np.random.randint(1, 11, size=(3, 4))
a10_2 = np.random.randint(1, 11, size=4)

print(a10_1)
print(a10_2)

print(np.dot(a10_1, a10_2))

[[ 1  7 10  2]
 [10  1  2  7]
 [10  7  6  6]]
[4 9 2 8]
[103 109 163]


In [17]:
a11_1 = np.random.random((2, 3))
a11_2 = np.random.random(3)
print(a11_1)
print(a11_2)

print(np.dot(a11_1, a11_2))

[[0.68876924 0.30457254 0.20047339]
 [0.65215004 0.63327852 0.62094135]]
[0.82993434 0.10324492 0.60112403]
[0.72358819 0.97988727]


In [18]:
a12_1 = np.random.randint(1, 11, size=(2, 2))
a12_2 = np.random.randint(1, 11, size=(2, 2))
print(a12_1)
print(a12_2)
print(np.multiply(a12_1, a12_2))

[[7 2]
 [4 9]]
[[2 8]
 [9 3]]
[[14 16]
 [36 27]]


In [19]:
a13_1 = np.random.randint(1, 11, size=(2, 2))
a13_2 = np.random.randint(1, 11, size=(2, 2))
print(a13_1)
print(a13_2)
print(np.dot(a13_1, a13_2))

[[5 6]
 [7 9]]
[[7 5]
 [1 6]]
[[41 61]
 [58 89]]


In [20]:
a14 = np.random.randint(1, 101, size=(5, 5))
print(a14)
print(np.sum(a14))

[[57 37 85 53 71]
 [28 30 43  3 23]
 [30 50 68  1 96]
 [37 60 44  9 69]
 [39 35 12 52 90]]
1122


In [22]:
a15_1 = np.random.randint(1, 11, size=(4, 4))
a15_2 = np.random.randint(1, 11, size=(4, 4))
print(a15_1)
print(a15_2)
print(a15_1 - a15_2)

[[ 8  9  4 10]
 [ 6  6 10  5]
 [ 1  1  6  1]
 [ 5  1  6 10]]
[[ 5  4 10  3]
 [ 6  5  6  5]
 [ 4 10  1  5]
 [ 1  3  3  9]]
[[ 3  5 -6  7]
 [ 0  1  4  0]
 [-3 -9  5 -4]
 [ 4 -2  3  1]]


In [24]:
a16 = np.random.random((3, 3))
print(a16)
print(np.sum(a16, axis=1).reshape((-1, 1)))

[[0.74036128 0.19298381 0.58684252]
 [0.9503993  0.52672056 0.03851617]
 [0.17303936 0.69612426 0.88527189]]
[[1.52018761]
 [1.51563603]
 [1.75443551]]


In [25]:
a17 = np.random.randint(1, 11, size=(3, 4))
print(a17)
print(np.square(a17))

[[1 1 1 2]
 [3 8 4 4]
 [5 6 5 7]]
[[ 1  1  1  4]
 [ 9 64 16 16]
 [25 36 25 49]]


In [26]:
a18 = np.random.randint(1, 50, size=4)
print(a18)
print(np.sqrt(a18))


[28 18 29 32]
[5.29150262 4.24264069 5.38516481 5.65685425]
